# Generated by Django 4.2.27 on 2026-03-21 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="区域名称"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
            ],
            options={
                "verbose_name": "区域",
                "verbose_name_plural": "区域",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HazardReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("description", models.TextField(verbose_name="描述")),
                (
                    "level",
                    models.CharField(
                        choices=[("general", "一般隐患"), ("major", "重大隐患")],
                        max_length=10,
                        verbose_name="等级",
                    ),
                ),
                (
                    "location_detail",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="具体位置"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待分派"),
                            ("fixing", "整改中"),
                            ("verifying", "待验证"),
                            ("closed", "已关闭"),
                            ("rejected", "驳回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="分派时间"
                    ),
                ),
                (
                    "fix_description",
                    models.TextField(blank=True, verbose_name="整改说明"),
                ),
                (
                    "fixed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="整改完成时间"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="验证时间"
                    ),
                ),
                (
                    "verify_remark",
                    models.TextField(blank=True, verbose_name="验证备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上报时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatched_hazards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分派人",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_hazards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="整改责任人",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="safety.location",
                        verbose_name="区域",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_hazards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上报人",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_hazards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="验证人",
                    ),
                ),
            ],
            options={
                "verbose_name": "隐患上报",
                "verbose_name_plural": "隐患上报",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HazardImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="hazards/%Y/%m/", verbose_name="图片"),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[("report", "上报"), ("fix", "整改")],
                        max_length=10,
                        verbose_name="阶段",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hazard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="safety.hazardreport",
                        verbose_name="隐患",
                    ),
                ),
            ],
            options={
                "verbose_name": "隐患图片",
                "verbose_name_plural": "隐患图片",
            },
        ),
    ]
