# Generated by Django 4.2.27 on 2026-03-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safety", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MezzanineRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                ("phone", models.CharField(max_length=20, verbose_name="手机号")),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="施工单位"
                    ),
                ),
                ("project", models.CharField(max_length=200, verbose_name="施工项目")),
                (
                    "check_in_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="入场时间"),
                ),
                (
                    "check_out_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="离场时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "夹层施工记录",
                "verbose_name_plural": "夹层施工记录",
                "ordering": ["-check_in_at"],
            },
        ),
    ]
