# Generated by Django 4.2.27 on 2026-03-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safety", "0002_mezzaninerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="mezzaninerecord",
            name="count",
            field=models.PositiveIntegerField(default=1, verbose_name="人数"),
        ),
    ]
