# Generated by Django 4.2.30 on 2026-04-16 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("safety", "0005_nightshiftcategory_nightshiftcheckitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NightShiftDuty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duty_date", models.DateField(verbose_name="值班日期")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待检查"), ("completed", "已完成")],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_duties",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="排班人",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nightshift_duties",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="检查人",
                    ),
                ),
                (
                    "record",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duty_ref",
                        to="safety.nightshiftrecord",
                        verbose_name="检查记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "夜班值班排班",
                "verbose_name_plural": "夜班值班排班",
                "ordering": ["-duty_date"],
                "unique_together": {("duty_date",)},
            },
        ),
        migrations.AddField(
            model_name="nightshiftrecord",
            name="duty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="safety.nightshiftduty",
                verbose_name="关联排班",
            ),
        ),
    ]
