# Generated by Django 4.2.30 on 2026-04-24 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("safety", "0008_rectification"),
    ]

    operations = [
        migrations.AddField(
            model_name="rectificationorder",
            name="verifier_assigned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="验证人分派时间"
            ),
        ),
        migrations.AddField(
            model_name="rectificationorder",
            name="verifier_assigner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispatched_verifier_rectifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="验证人分派人",
            ),
        ),
        migrations.AlterField(
            model_name="rectificationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "创建"),
                    ("assign", "分派"),
                    ("reassign", "改派"),
                    ("assign_verifier", "分派验证人"),
                    ("submit_rectify", "提交整改"),
                    ("verify_pass", "验证通过"),
                    ("verify_reject", "验证驳回"),
                    ("cancel", "取消"),
                    ("auto_overdue", "逾期标记"),
                ],
                max_length=30,
                verbose_name="操作",
            ),
        ),
        migrations.CreateModel(
            name="RectificationNotifyRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "全部来源"),
                            ("hazard_report", "安全隐患上报"),
                            ("dustroom_inspection", "除尘房巡检"),
                            ("nightshift_check", "夜班监护检查"),
                        ],
                        default="",
                        help_text="留空表示所有来源；否则仅匹配的来源会触发通知",
                        max_length=30,
                        verbose_name="来源过滤",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="启用")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rectification_notify_subs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="通知接收人",
                    ),
                ),
            ],
            options={
                "verbose_name": "整改通知接收人",
                "verbose_name_plural": "整改通知接收人",
                "ordering": ["user_id"],
                "unique_together": {("user", "source_type")},
            },
        ),
    ]
