# Generated by Django 4.2.27 on 2026-03-16 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlarmRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("warning", "预警"), ("alarm", "报警")],
                        max_length=20,
                        verbose_name="级别",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "未处理"),
                            ("acknowledged", "已确认"),
                            ("resolved", "已解决"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("triggered_value", models.FloatField(verbose_name="触发值")),
                ("threshold_value", models.FloatField(verbose_name="阈值")),
                (
                    "triggered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="触发时间"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="处理备注"),
                ),
                (
                    "monitor_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarms",
                        to="equipment.monitorpoint",
                        verbose_name="监控点",
                    ),
                ),
            ],
            options={
                "verbose_name": "报警记录",
                "verbose_name_plural": "报警记录",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="ThresholdRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warning_high",
                    models.FloatField(blank=True, null=True, verbose_name="预警上限"),
                ),
                (
                    "warning_low",
                    models.FloatField(blank=True, null=True, verbose_name="预警下限"),
                ),
                (
                    "alarm_high",
                    models.FloatField(blank=True, null=True, verbose_name="报警上限"),
                ),
                (
                    "alarm_low",
                    models.FloatField(blank=True, null=True, verbose_name="报警下限"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "monitor_point",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threshold",
                        to="equipment.monitorpoint",
                        verbose_name="监控点",
                    ),
                ),
            ],
            options={
                "verbose_name": "阈值规则",
                "verbose_name_plural": "阈值规则",
            },
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(verbose_name="采集值")),
                (
                    "recorded_at",
                    models.DateTimeField(db_index=True, verbose_name="采集时间"),
                ),
                (
                    "monitor_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="equipment.monitorpoint",
                        verbose_name="监控点",
                    ),
                ),
            ],
            options={
                "verbose_name": "传感器数据",
                "verbose_name_plural": "传感器数据",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="RepairAdvice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ai_response", models.TextField(verbose_name="AI回复")),
                (
                    "ragflow_context",
                    models.TextField(
                        blank=True, default="", verbose_name="知识库上下文"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "alarm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repair_advice",
                        to="monitoring.alarmrecord",
                        verbose_name="报警记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "维修建议",
                "verbose_name_plural": "维修建议",
            },
        ),
    ]
