# Generated by Django 4.2.27 on 2026-03-16 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="设备名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="设备编号"
                    ),
                ),
                ("location", models.CharField(max_length=200, verbose_name="安装地点")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "运行中"),
                            ("stopped", "停机"),
                            ("fault", "故障"),
                        ],
                        default="stopped",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "设备",
                "verbose_name_plural": "设备",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonitorPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="监控点名称")),
                ("param_key", models.CharField(max_length=50, verbose_name="参数标识")),
                ("unit", models.CharField(max_length=20, verbose_name="单位")),
                (
                    "param_type",
                    models.CharField(
                        choices=[
                            ("temperature", "温度"),
                            ("current", "电流"),
                            ("vibration", "振动"),
                        ],
                        max_length=20,
                        verbose_name="参数类型",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitor_points",
                        to="equipment.equipment",
                        verbose_name="所属设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "监控点",
                "verbose_name_plural": "监控点",
                "unique_together": {("equipment", "param_key")},
            },
        ),
    ]
