# Generated by Django 4.2.27 on 2026-03-19 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionInterface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interface_type",
                    models.CharField(
                        choices=[("http", "HTTP"), ("mqtt", "MQTT")],
                        max_length=10,
                        verbose_name="接口类型",
                    ),
                ),
                ("config", models.JSONField(default=dict, verbose_name="配置参数")),
                (
                    "polling_interval",
                    models.IntegerField(default=60, verbose_name="轮询间隔(秒)"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "monitor_point",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection",
                        to="equipment.monitorpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "采集接口",
                "verbose_name_plural": "采集接口",
            },
        ),
    ]
