# Generated by Django 4.2.27 on 2026-03-28 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="牌号名称"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "quality_brand",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MoistureData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sampling_date", models.DateField(verbose_name="取样日期")),
                (
                    "sample_number",
                    models.CharField(max_length=100, verbose_name="样品编号"),
                ),
                (
                    "machine_number",
                    models.CharField(max_length=50, verbose_name="机台号"),
                ),
                ("machine_stage", models.CharField(max_length=50, verbose_name="机台")),
                (
                    "finished_moisture",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="成品水分",
                    ),
                ),
                (
                    "moisture_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="含丝率",
                    ),
                ),
                (
                    "addition_method",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="加丝方式/加丝机",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="批次号"
                    ),
                ),
                (
                    "batch_moisture",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="批次水分",
                    ),
                ),
                (
                    "drying_moisture",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="烘丝水分",
                    ),
                ),
                (
                    "mixed_moisture",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="混合丝水分",
                    ),
                ),
                (
                    "cabinet_moisture",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="出柜水分",
                    ),
                ),
                (
                    "rolling_moisture",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="卷丝水分",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moisture_data",
                        to="quality.brand",
                    ),
                ),
            ],
            options={
                "db_table": "quality_moisture_data",
                "ordering": ["-sampling_date", "-created_at"],
            },
        ),
    ]
