# Generated by Django 4.2.30 on 2026-04-16 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("safety", "0003_mezzaninerecord_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="DustRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="名称"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="编号"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "除尘房",
                "verbose_name_plural": "除尘房",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="InspectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="检查项名称")),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("checkbox", "正常/异常"),
                            ("number", "数值"),
                            ("text", "文本"),
                            ("select", "选择"),
                        ],
                        default="checkbox",
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='select 类型时填写，如 ["好","中","差"]',
                        verbose_name="选项列表",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="number 类型时填写，如 ℃",
                        max_length=50,
                        verbose_name="单位",
                    ),
                ),
                ("required", models.BooleanField(default=True, verbose_name="必填")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "巡检检查项",
                "verbose_name_plural": "巡检检查项",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="InspectionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("electrical", "电气修理工"),
                            ("mechanical", "机械修理工"),
                            ("operator", "操作工"),
                            ("safety", "安全员"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="巡检角色",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "每天"),
                            ("per_shift", "每班次"),
                            ("weekly", "每周"),
                            ("monthly", "每月"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="巡检频次",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
            ],
            options={
                "verbose_name": "巡检模板",
                "verbose_name_plural": "巡检模板",
            },
        ),
        migrations.CreateModel(
            name="InspectionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inspection_date", models.DateField(verbose_name="巡检日期")),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "进行中"), ("submitted", "已提交")],
                        default="in_progress",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "has_abnormal",
                    models.BooleanField(default=False, verbose_name="存在异常"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提交时间"
                    ),
                ),
                (
                    "dust_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_records",
                        to="safety.dustroom",
                        verbose_name="除尘房",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="巡检人",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="safety.inspectiontemplate",
                        verbose_name="巡检模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "巡检记录",
                "verbose_name_plural": "巡检记录",
                "ordering": ["-inspection_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InspectionItemResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, verbose_name="填写值")),
                (
                    "is_normal",
                    models.BooleanField(default=True, verbose_name="是否正常"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="异常备注")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="safety.inspectionitem",
                        verbose_name="检查项",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="safety.inspectionrecord",
                        verbose_name="巡检记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "检查项结果",
                "verbose_name_plural": "检查项结果",
            },
        ),
        migrations.AddField(
            model_name="inspectionitem",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="safety.inspectiontemplate",
                verbose_name="所属模板",
            ),
        ),
        migrations.CreateModel(
            name="DustRoomInspector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("electrical", "电气修理工"),
                            ("mechanical", "机械修理工"),
                            ("operator", "操作工"),
                            ("safety", "安全员"),
                        ],
                        max_length=20,
                        verbose_name="巡检角色",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dustroom_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "除尘房巡检人员",
                "verbose_name_plural": "除尘房巡检人员",
                "unique_together": {("user", "role")},
            },
        ),
    ]
