# Generated by Django 4.2.30 on 2026-04-16 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("safety", "0004_dustroom_inspectionitem_inspectiontemplate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NightShiftCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分类名称"
                    ),
                ),
                (
                    "allows_custom",
                    models.BooleanField(
                        default=False,
                        help_text="重点检查部位允许巡检人员自行添加检查条目",
                        verbose_name="允许自填项",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
            ],
            options={
                "verbose_name": "夜班检查分类",
                "verbose_name_plural": "夜班检查分类",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="NightShiftCheckItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="检查项名称")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="safety.nightshiftcategory",
                        verbose_name="所属分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "夜班检查预置项",
                "verbose_name_plural": "夜班检查预置项",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="NightShiftRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inspection_date", models.DateField(verbose_name="巡检日期")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("submitted", "已提交")],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "has_issues",
                    models.BooleanField(default=False, verbose_name="存在问题"),
                ),
                (
                    "overall_remark",
                    models.TextField(blank=True, verbose_name="整体备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提交时间"
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nightshift_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="巡检人",
                    ),
                ),
            ],
            options={
                "verbose_name": "夜班检查记录",
                "verbose_name_plural": "夜班检查记录",
                "ordering": ["-inspection_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NightShiftIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="问题描述")),
                (
                    "rectification",
                    models.TextField(blank=True, verbose_name="整改情况"),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="已整改"),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="safety.nightshiftrecord",
                        verbose_name="检查记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "夜班发现问题",
                "verbose_name_plural": "夜班发现问题",
            },
        ),
        migrations.CreateModel(
            name="NightShiftCheckResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_name",
                    models.CharField(
                        blank=True,
                        help_text="重点检查部位允许巡检人员自填",
                        max_length=200,
                        verbose_name="自填项名称",
                    ),
                ),
                (
                    "is_normal",
                    models.BooleanField(default=True, verbose_name="是否正常"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="异常备注")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="safety.nightshiftcategory",
                        verbose_name="分类",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        help_text="自填项时为空",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="safety.nightshiftcheckitem",
                        verbose_name="预置检查项",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="safety.nightshiftrecord",
                        verbose_name="检查记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "夜班检查结果",
                "verbose_name_plural": "夜班检查结果",
            },
        ),
    ]
