# Generated by Django 4.2.27 on 2026-03-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moisturedata",
            name="batch_moisture",
        ),
        migrations.RemoveField(
            model_name="moisturedata",
            name="moisture_rate",
        ),
        migrations.AddField(
            model_name="moisturedata",
            name="powder_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="含末率",
            ),
        ),
        migrations.AddField(
            model_name="moisturedata",
            name="shift",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="班次"
            ),
        ),
    ]
