# Generated by Django 4.2.27 on 2026-03-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0002_remove_moisturedata_batch_moisture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moisturedata",
            name="sampling_date",
            field=models.DateField(blank=True, null=True, verbose_name="取样日期"),
        ),
    ]
