# Generated by Django 4.2.27 on 2026-03-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0003_alter_moisturedata_sampling_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moisturedata",
            name="rolling_moisture",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="卷制水分",
            ),
        ),
    ]
